spring.application.name=grupofamiliar_backend

# ============================================
# Base de Datos
# ============================================
# conexion local
#spring.datasource.url=jdbc:mariadb://localhost:3306/grupo_familiar
#spring.datasource.username=root
#spring.datasource.password=
#spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# conexion publica de railway
#spring.datasource.url=jdbc:mariadb://trolley.proxy.rlwy.net:37698/grupofamiliar?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=t-7pSiHMjsiwBw66dsQKcqpfC7oerJee
#spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# conexion privada de railway
spring.datasource.url=jdbc:mariadb://${MARIADB_HOST}:${MARIADB_PORT}/${MARIADB_DATABASE}
spring.datasource.username=${MARIADB_USER}
spring.datasource.password=${MARIADB_ROOT_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Optimización de Pool de Conexiones HikariCP para entornos de bajo consumo
spring.datasource.hikari.maximum-pool-size=4
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=60000
spring.datasource.hikari.max-lifetime=1800000

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

# IMPORTANTE: Para ejecutar scripts SQL automticos
# spring.sql.init.mode=always
# spring.sql.init.platform=mysql
# spring.sql.init.encoding=UTF-8

# Esto permite ejecutar el script incluso si hay datos existentes
# spring.jpa.defer-datasource-initialization=true

# ============================================
# JWT Configuration
# ============================================
app.jwt.secret=your-super-secret-key-change-this-in-production-environment-very-important-key-256bit-minimum
app.jwt.access-token-expiration=900000
app.jwt.refresh-token-expiration=604800000

# ============================================
# Server Configuration
# ============================================
server.port=8080
server.servlet.context-path=/api

# ============================================
# Email Configuration
# ============================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pablojc3005@gmail.com
spring.mail.password=lyoi juws htus yhdm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# ============================================
# Logging
# ============================================
logging.level.root=INFO
logging.level.com.example.grupofamiliar_backend=INFO
logging.level.org.springframework.security=INFO
